// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/Vdtry-06/clean-architecture-go-ent/ent/book"
	"github.com/Vdtry-06/clean-architecture-go-ent/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	bookFields := schema.Book{}.Fields()
	_ = bookFields
	// bookDescTitle is the schema descriptor for title field.
	bookDescTitle := bookFields[0].Descriptor()
	// book.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	book.TitleValidator = bookDescTitle.Validators[0].(func(string) error)
	// bookDescAuthor is the schema descriptor for author field.
	bookDescAuthor := bookFields[1].Descriptor()
	// book.AuthorValidator is a validator for the "author" field. It is called by the builders before save.
	book.AuthorValidator = bookDescAuthor.Validators[0].(func(string) error)
	// bookDescPrice is the schema descriptor for price field.
	bookDescPrice := bookFields[2].Descriptor()
	// book.PriceValidator is a validator for the "price" field. It is called by the builders before save.
	book.PriceValidator = bookDescPrice.Validators[0].(func(float64) error)
	// bookDescPublishYear is the schema descriptor for publish_year field.
	bookDescPublishYear := bookFields[3].Descriptor()
	// book.PublishYearValidator is a validator for the "publish_year" field. It is called by the builders before save.
	book.PublishYearValidator = bookDescPublishYear.Validators[0].(func(int) error)
}
